project:
  type: website
  output-dir: docs

website:
  title: "Mary W"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - file: Mini_Project 3 Strings and Sentiment.qmd
        text: "String Analysis"
      - file: WI_Gerrymandering.qmd
        text: "Wisconsin Gerrymandering"
      - file: US_States_and_Minimum_Wage.qmd
        text: "Minimum Wage in the United States"
      - file: Mini Project Simulations.qmd
        text: "Mini Project - Simulations"
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-overflow: wrap

editor: visual

