project:
  type: website
  output-dir: docs

website:
  title: "Mary W"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - file: Mini Project 3 Strings and Sentiment
        text: "String Analysis"
        

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

